ArchevaleTown_WaveyHouse_MapScripts::
	.byte 0


WaveyHouse_EventScript::
# 4 "data/maps/ArchevaleTown_WaveyHouse/scripts.pory"
	lock
# 5 "data/maps/ArchevaleTown_WaveyHouse/scripts.pory"
	faceplayer
# 6 "data/maps/ArchevaleTown_WaveyHouse/scripts.pory"
	msgbox WaveyHouse_EventScript_Text_0
# 7 "data/maps/ArchevaleTown_WaveyHouse/scripts.pory"
	release
	return


WaveyHouse_EventScript_Text_0:
# 6 "data/maps/ArchevaleTown_WaveyHouse/scripts.pory"
	.string "I should talk to her...$"
