ArchevaleTown_WindaHouse_MapScripts::
	.byte 0


WindaHouse_EventScript::
# 4 "data/maps/ArchevaleTown_WindaHouse/scripts.pory"
	lock
# 5 "data/maps/ArchevaleTown_WindaHouse/scripts.pory"
	faceplayer
# 6 "data/maps/ArchevaleTown_WindaHouse/scripts.pory"
	msgbox WindaHouse_EventScript_Text_0
# 7 "data/maps/ArchevaleTown_WindaHouse/scripts.pory"
	release
	return


WindaHouse_EventScript_Text_0:
# 6 "data/maps/ArchevaleTown_WindaHouse/scripts.pory"
	.string "I'd like to go with him to that resort in\n"
	.string "a faraway region...$"
